Tracker:AddLocations("locations/Any Region.json")
Tracker:AddLocations("locations/Badge Masks.json")
Tracker:AddLocations("locations/Badlands.json")
Tracker:AddLocations("locations/Chum Locations.json")
Tracker:AddLocations("locations/Ewer.json")
Tracker:AddLocations("locations/Hakoa.json")
Tracker:AddLocations("locations/Redsee.json")
Tracker:AddLocations("locations/Sansee.json")
Tracker:AddLocations("locations/Sodic Waste.json")
Tracker:AddLocations("locations/The Wash.json")
Tracker:AddLocations("locations/Overworld.json")
